### ISSUE TITLE
Plan for website overhaul

### ISSUE THREAD

**Issue by wtip** [bahaidev/qiblih-website#1]
The website is currently not very functional due to changes to the Google Maps API in June 2018 https://cloud.google.com/maps-platform/user-guide/

The priority is to get the current site functional so that it's not just showing "This page can't load Google Maps correctly."

Here are some of my wishes for updating the site:

- [X]  merge the qiblih.com and m.qiblih.com sites.
- [x]  decide on what mobile functionality is needed on the website vs linking to app store versions.
- [X]  convert to static site so that we can host on https://www.netlify.com/
  PHP use isn't really necessary 
- [x] visual update with responsive design
- [ ]  add additional study resources
- [ ] multilingual (probably should use some static cms like Hugo for this)
- [x] Google maps api alternative? Is Google maps blocked is some countries?

**Comment by brettz9** [comment]
This is awesome! Great to have your project here, and hope volunteers will be forthcoming... My own plate is rather full at the moment, unfortunately, but might you put the code for m.qiblih.com as a branch and link to the branch so it is available for any volunteers who might assist with the merge?

As far as resources, FWIW, we have a few quotes on the topic at https://bahai9.com/wiki/Qiblih

**Comment by wtip** [comment]
I'm going to let @janrg commit the code for the mobile site since it's his creation. He's mentioned that he's busy till sometime in December.

**Comment by wtip** [comment]
I've enabled auto deployments for the `development` branch that will show up under this domain https://development.qiblih.com

**Comment by wtip** [comment]
@brettz9 I've pushed out changes for a completely new site. Feel free to leave some feedback if you have time.

**Comment by brettz9** [comment]
Looking at https://qiblih.com , that is sweet! Just got my permission for location and went right to the map even in China... Great! Nice user experience and useful utility...

And it's wonderful to see this development taking place under a collaborative Bahá'í umbrella (even general service projects can be added in this bahaidev group).

Is it ready for a full release then? If so, I can let others know too...

(Btw, I first looked at https://development.qiblih.com so you might want to update that or reference to it in your comment above.)

**Comment by wtip** [comment]
@brettz9 I was going to email a few people to have them review the site before I put out some kind of mailing list announcement. So maybe wait until the weekend before you let too many people know.

**Comment by brettz9** [comment]
Is this from the `development` branch then or `master`? (I was thinking of taking a look to do some minor linting as I am fond to do, and possibly if it is ok, add ESLint via npm, as is the convention for web apps these days...)

**Comment by brettz9** [comment]
Also, what do you say to converting to ES6 Modules and Babel using Rollup? One could still do most testing in modern browsers with source, but it would add a build step for production to support older browsers, the advantage being more clean and efficient, standards-based modular code.

**Comment by brettz9** [comment]
And if you're new to any of it, I'd be happy to show you the ropes...

**Comment by brettz9** [comment]
Btw, in case I forget, you'll probably want to update the links at https://bahaipedia.org/Qiblih and https://bahai9.com/wiki/Qiblih#Resources
