### ISSUE TITLE
Generate new Google Maps API key

### ISSUE THREAD

**Issue by wtip** [bahaidev/qiblih-website#3]
https://cloud.google.com/maps-platform/user-guide/
Google Maps API now requires using an API key linked to a billable Google Cloud account.

> When you enable billing, you get $200 free usage every month for Maps, Routes, or Places.

You can restrict the Maps JavaScript API usage with HTTP referrers settings. https://cloud.google.com/docs/authentication/api-keys
You can also limit the Map loads per day so that you stay below the $200/month

**Comment by wtip** [comment]
We need to determine how to set the API Quotas to stay below the free usage limit.
I think we need to use the Dynamic Maps SKU which would let us do "up to 28,000 loads" month.
 https://developers.google.com/maps/billing/understanding-cost-of-use
https://cloud.google.com/maps-platform/pricing/sheet/
https://mapsplatformtransition.withgoogle.com/calculator

**Comment by sjrahimian** [comment]
Is it not possible to use an alternative API (OpenLayers, Leaflet, etc.) and avoid Google Maps API pricing altogether?

**Comment by wtip** [comment]
My guess is that it is possible to use another maps data source and JavaScript library to accomplish this though I haven't looked into these options and I don't know what the restrictions are.
With the amount of traffic that the site gets I don't think the Google maps API free quota is going to be problem.
I think the biggest hurdle at the moment might be ease of implementation. I personally haven't had time to dig into any solution (Google or otherwise).
@diveresque recently contacted me to offer to help fix the Maps code. It might be worth having a group discussion if you are interested in helping as well.

**Comment by sjrahimian** [comment]
> With the amount of traffic that the site gets I don't think the Google maps API free quota is going to be problem.

I thought of that after making the post; should've been my first question.

I'm interested in helping out, however, not entirely certain when that will be possible :disappointed:. Currently it seems after the first week of March (a major project that has to be wrapped up this month + life in final semester). If you and @diveresque don't mind me being in the shadows for the next month or so, by all means include me in the discussion.

**Comment by brettz9** [comment]
You might consider an abstracted map library like http://mapstraction.com/ to potentially minimize lock-in...

**Comment by wtip** [comment]
@brettz9 this is an interesting idea though it's a bit concerning that the project hasn't had a release in 5 years and the last commit was 4 years ago.

**Comment by brettz9** [comment]
Yeah... Maybe https://openlayers.org/ or https://leafletjs.com/ ? See https://gis.stackexchange.com/questions/33918/choosing-openlayers-or-leaflet for some opinions on choosing between them...

**Comment by diveresque** [comment]
The new API key has been added to the development site and seems to have fixed the existing error, although the map doesn't display yet, possibly needs an upgrade to version 3. I dont have that much experience with it, but will see how it goes, @sjrahimian whenever you have time to look as we go and if you have any input it would be welcomed :)
